### ISSUE TITLE
Telnet Connection closed

### ISSUE THREAD

**Issue by Multivit4min** [benediktschmitt/py-ts3#11]
I am currently running a bot wich now was running 7 hours straight until it closed the connection for some reason, currently i am reloading the clientlist every 2 seconds so it can not be a Server Timeout

Traceback (most recent call last):
  File "start.py", line 24, in <module>
    Bot = bot.Bot(config).run()
  File "/home/python/bot.py", line 68, in run
    cycler(self)
  File "/home/python/bot.py", line 82, in __call__
    self.execute(bot)
  File "/home/python/bot.py", line 106, in execute
    self.cinfo = bot.ts3conn.clientinfo(clid=self.client['clid'])
  File "/home/python/ts3/commands.py", line 1360, in clientinfo
    return self._return_proxy("clientinfo", cparams, uparams, options)
  File "/home/python/ts3/query.py", line 636, in _return_proxy
    self, command, common_parameters, unique_parameters, options)
  File "/home/python/ts3/query.py", line 613, in send
    return self.wait_for_resp(query_id, timeout)
  File "/home/python/ts3/query.py", line 441, in wait_for_resp
    raise TS3ResponseRecvError()
ts3.query.TS3ResponseRecvError: Could not receive the response from the server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/python/ts3/query.py", line 510, in recv
    b"\n\r", timeout=poll_intervall)
  File "/usr/lib/python3.2/telnetlib.py", line 293, in read_until
    return self._read_until_with_poll(match, timeout)
  File "/usr/lib/python3.2/telnetlib.py", line 340, in _read_until_with_poll
    return self.read_very_lazy()
  File "/usr/lib/python3.2/telnetlib.py", line 452, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/home/python/ts3/query.py", line 546, in recv
    self.close()
  File "/home/python/ts3/query.py", line 271, in close
    self._telnet_conn.write(b"quit\n\r")
  File "/usr/lib/python3.2/telnetlib.py", line 282, in write
    self.sock.sendall(buffer)
socket.error: [Errno 32] Broken pipe

**Comment by benediktschmitt** [comment]
To be honest, I have no idea.

Did the ts3 server logged anything?

**Comment by Multivit4min** [comment]
It only got a connection lost not more :/

**Comment by benediktschmitt** [comment]
Are you connected over a network or direct via *localhost*?

**Comment by Multivit4min** [comment]
I am connected from a different Machine in a Local Network

**Comment by benediktschmitt** [comment]
Perhaps your connection dropped for a short time. Is this bug reproducible?

**Comment by Multivit4min** [comment]
Hmm at the same time i reloaded the Firewall to the Network all the Traffic gets routed over it and i am not sure if it was with the reload of it ...

I just report you if i get the same Error again

**Comment by benjbubu** [comment]
I got the same issue. I try to develop a bridge between a IRC bot and Teamspeak with your library. 
After a while i got an EOF telnet connection closed without reason. Teamspeak is running on the same machine and i got this only message 

Exception in thread Thread-178:
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.3/threading.py", line 594, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abraxus/virtualenv/willie/lib/python3.3/site-packages/ts3/query.py", line 520, in recv
    b"\n\r", timeout=poll_intervall)
  File "/usr/local/lib/python3.3/telnetlib.py", line 293, in read_until
    return self._read_until_with_poll(match, timeout)
  File "/usr/local/lib/python3.3/telnetlib.py", line 340, in _read_until_with_poll
    return self.read_very_lazy()
  File "/usr/local/lib/python3.3/telnetlib.py", line 452, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

**Comment by SentinelX101** [comment]
I have experienced the same error recently, my bot crashed after it had been running for around 25 hours on the same machine as the Teamspeak server (which also happens to be a dedicated Linux server running only Teamspeak and the bot, so should not have been experiencing any interference from other running programs). It seems rather random and so far I have not been able to reproduce this bug.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.2/threading.py", line 740, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.2/threading.py", line 693, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.2/dist-packages/ts3/query.py", line 510, in recv
    b"\n\r", timeout=poll_intervall)
  File "/usr/lib/python3.2/telnetlib.py", line 293, in read_until
    return self._read_until_with_poll(match, timeout)
  File "/usr/lib/python3.2/telnetlib.py", line 340, in _read_until_with_poll
    return self.read_very_lazy()
  File "/usr/lib/python3.2/telnetlib.py", line 452, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

**Comment by benediktschmitt** [comment]
I'll run some tests this week.

If anyone has an idea how the bug could be fixed, please let me know :)

**Comment by benjbubu** [comment]
mmm for now, i think on a dirty fix : relaunch the connection when python tell EOFError : telnet connection closed.. But it's sure there is a proper way :)

**Comment by benediktschmitt** [comment]
I thought about this fix too. But there is no easy way to simply *resume* the session. The fix would not make sure the client is *logged in* or listens to any event.

**Comment by benjbubu** [comment]
It seems this issue does not come from your python-ts3 or the server. I believe it comes from telnet itself. With my script, i lost the connection every 10 minutes if there is no command received. So i pass this issue with sending a ts3.serverinfo command every 5 min to keep the connection.

**Comment by benediktschmitt** [comment]
@benjbubu thank you. I forgot the max_idle_time settings (default value: 600s). This problem has been solved in issue #6 .

**Comment by benediktschmitt** [comment]
Did the *keepalive()* method fix the problem?

**Comment by SentinelX101** [comment]
@benediktschmitt I believe that the issue experienced by myself and @Multivit4min is different from the issue experienced by @benjbubu. I have been using keepalive(interval=60) and issuing the clientlist() command every 10 seconds since I started my bot.

The original issue still seems to be present and is as random as ever, from my tests the bot seems to crash somewhere between the first 24 - 72 hours of running at random. I've also been logging the commands that my bot performs just before the crash and there seems to be no pattern.

I plan to run a minimal script with only the keepalive(interval=60) method soon to confirm that nothing in my more complicated script is creating this error. It would be useful is someone else could do the same (for 72+ hours) so that we can be sure that this is an API problem.

**Comment by Ahmed-90** [comment]
Hello,
@SentinelX101 & @Multivit4min 
I'm interested in using this package to build a daemon so is this issue still there? is it related to py-ts3 or just network/protocol issue??

would love to get an answer :smiley: 

Thanks

**Comment by benediktschmitt** [comment]
It's been a long time, but here are my test results: It seems that it is the same *bug* as issue #6 . I used this script for testing:
```Python
#!/usr/bin/env python3

import ts3
import time

USER = "serveradmin"
PASS = "..."
HOST = "localhost"

@ts3.query.TS3Connection.on_event.connect
def event_handler(sender, event):
    """
    """
    print("Event received:")
    print("\t", sender)
    print("\t", event.event)
    return None

with ts3.query.TS3Connection(host = HOST) as ts3conn:

    # Login and select the server.
    ts3conn.login(client_login_name = USER, client_login_password = PASS)
    ts3conn.use(sid = 1)

    # Subscribe to all channels.
    ts3conn.servernotifyregister(event = "server")
    ts3conn.servernotifyregister(event = "textserver")

    # Listen to "League Of Legends\Normal"
    ts3conn.servernotifyregister(event = "channel", id_ = 5)
    ts3conn.servernotifyregister(event = "textprivate", id_ = 5)
    ts3conn.servernotifyregister(event = "textchannel", id_ = 5)

    # Wait for events.
    ts3conn.keepalive()
    try:
      ts3conn.recv(recv_forever = True)
    except Exception as err:
      print(err)
      print(time.time())
      print(time.ctime())
```

This *bot* is running now for more than 5 days. Without using the ``tsconn.keepalive()`` method, the connection was closed after 10 minutes by the server.

**Comment by tomabrafix** [comment]
Another cause for this error could be the anti-flood protection from the teamspeak server. Don't forget to add your local ip to the whitelist:

	$ echo "192.168.178.42" >> path/to/ts3/server/directory/query_ip_whitelist.txt
